version: "3"

services:

  avitoback:
    build:
      context: "../.."
      dockerfile: "deploy/dev/go/Dockerfile"
    hostname: "avitoback"
    ports:
      - "5000:5000"
      - "8080:8080"
    restart: always
